/**
 * PDF report document using @react-pdf/renderer (DEC-027).
 * Maps ReportContent to styled PDF primitives.
 */

import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import type { ReportContent } from '@/types/database';

const NAVY = '#1E3A5F';
const VERDICT_COLORS: Record<string, string> = {
  pursue: '#22C55E',
  refine: '#F59E0B',
  test_first: '#3B82F6',
  drop: '#EF4444',
  insufficient_data: '#6B7280',
};

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  header: { backgroundColor: NAVY, padding: 20, marginBottom: 20, marginHorizontal: -40, marginTop: -40 },
  headerTitle: { color: '#fff', fontSize: 8, letterSpacing: 1, textTransform: 'uppercase' as const },
  headerIdea: { color: '#fff', fontSize: 16, fontWeight: 'bold', marginTop: 6 },
  verdictBanner: { padding: 16, borderRadius: 6, marginBottom: 16 },
  verdictLabel: { fontSize: 20, fontWeight: 'bold', color: '#fff' },
  verdictScore: { fontSize: 32, fontWeight: 'bold', color: '#fff', marginTop: 4 },
  verdictOneLiner: { fontSize: 10, color: '#fff', marginTop: 4, opacity: 0.9 },
  sectionTitle: { fontSize: 13, fontWeight: 'bold', color: NAVY, marginTop: 16, marginBottom: 8 },
  text: { fontSize: 10, lineHeight: 1.5, marginBottom: 4 },
  dimRow: { flexDirection: 'row' as const, justifyContent: 'space-between' as const, paddingVertical: 4, borderBottomWidth: 0.5, borderBottomColor: '#e5e5e5' },
  dimName: { fontSize: 10, fontWeight: 'bold', width: '40%' },
  dimScore: { fontSize: 10, width: '15%', textAlign: 'center' as const },
  dimConf: { fontSize: 9, width: '15%', textAlign: 'center' as const, color: '#666' },
  dimReasoning: { fontSize: 9, width: '30%', color: '#444' },
  flag: { flexDirection: 'row' as const, marginBottom: 4 },
  flagDot: { width: 6, height: 6, borderRadius: 3, marginTop: 3, marginRight: 6 },
  flagText: { fontSize: 9, flex: 1 },
  nextStep: { flexDirection: 'row' as const, marginBottom: 6 },
  stepNumber: { fontSize: 10, fontWeight: 'bold', color: NAVY, width: 20 },
  stepText: { fontSize: 10, flex: 1 },
  qaQuestion: { fontSize: 9, color: '#666', marginBottom: 2 },
  qaAnswer: { fontSize: 10, marginBottom: 8 },
  footer: { position: 'absolute' as const, bottom: 20, left: 40, right: 40, flexDirection: 'row' as const, justifyContent: 'space-between' as const },
  footerText: { fontSize: 7, color: '#999' },
});

interface ReportPDFDocumentProps {
  report: ReportContent;
  ideaTitle: string;
}

export function ReportPDFDocument({ report, ideaTitle }: ReportPDFDocumentProps) {
  const verdictStr = report.verdict?.verdict ?? 'insufficient_data';
  const verdictColor = VERDICT_COLORS[verdictStr] ?? '#6B7280';
  const score = report.verdict?.score ?? 0;
  const confidence = report.verdict?.confidence ?? 0;

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.headerTitle}>Kill My Idea — Analysis Report</Text>
          <Text style={styles.headerIdea}>{ideaTitle}</Text>
        </View>

        {/* Verdict Banner */}
        <View style={[styles.verdictBanner, { backgroundColor: verdictColor }]}>
          <Text style={styles.verdictLabel}>{verdictStr.replace('_', ' ').toUpperCase()}</Text>
          <Text style={styles.verdictScore}>{score.toFixed(1)}/10</Text>
          <Text style={styles.verdictOneLiner}>
            {report.verdict?.one_liner ?? ''} (Confidence: {Math.round(confidence * 100)}%)
          </Text>
        </View>

        {/* Executive Summary */}
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <Text style={styles.text}>{report.executive_summary}</Text>

        {/* Dimension Scores */}
        <Text style={styles.sectionTitle}>Dimension Scores</Text>
        <View style={styles.dimRow}>
          <Text style={[styles.dimName, { color: '#666', fontWeight: 'normal' }]}>Dimension</Text>
          <Text style={[styles.dimScore, { color: '#666' }]}>Score</Text>
          <Text style={styles.dimConf}>Confidence</Text>
          <Text style={[styles.dimReasoning, { color: '#666' }]}>Key Finding</Text>
        </View>
        {(report.dimension_reasoning ?? []).map((dim, i) => (
          <View key={i} style={styles.dimRow}>
            <Text style={styles.dimName}>{dim.dimension}</Text>
            <Text style={styles.dimScore}>{dim.score.toFixed(1)}</Text>
            <Text style={styles.dimConf}>—</Text>
            <Text style={styles.dimReasoning}>{dim.reasoning.slice(0, 80)}...</Text>
          </View>
        ))}

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by Kill My Idea</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>

      {/* Page 2: Detailed Analysis */}
      <Page size="A4" style={styles.page}>
        {/* Red Flags */}
        {report.red_flags && report.red_flags.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Red Flags</Text>
            {report.red_flags.map((flag, i) => (
              <View key={i} style={styles.flag}>
                <View style={[styles.flagDot, { backgroundColor: '#EF4444' }]} />
                <Text style={styles.flagText}>[{flag.severity}] {flag.text}</Text>
              </View>
            ))}
          </>
        )}

        {/* Green Flags */}
        {report.green_flags && report.green_flags.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Green Flags</Text>
            {report.green_flags.map((flag, i) => (
              <View key={i} style={styles.flag}>
                <View style={[styles.flagDot, { backgroundColor: '#22C55E' }]} />
                <Text style={styles.flagText}>[{flag.strength}] {flag.text}</Text>
              </View>
            ))}
          </>
        )}

        {/* Clarification Answers */}
        {report.clarification_qa && report.clarification_qa.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Your Answers</Text>
            {report.clarification_qa.map((qa, i) => (
              <View key={i}>
                <Text style={styles.qaQuestion}>Q [{qa.dimension}]: {qa.question}</Text>
                <Text style={styles.qaAnswer}>{qa.answer}</Text>
              </View>
            ))}
          </>
        )}

        {/* Next Steps */}
        {report.next_steps && report.next_steps.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Next Steps</Text>
            {report.next_steps.map((step, i) => (
              <View key={i} style={styles.nextStep}>
                <Text style={styles.stepNumber}>{step.priority}.</Text>
                <Text style={styles.stepText}>{step.action}</Text>
              </View>
            ))}
          </>
        )}

        {/* Weaknesses & Suggestions */}
        {report.weaknesses && (
          <>
            <Text style={styles.sectionTitle}>Weaknesses</Text>
            <Text style={styles.text}>{report.weaknesses}</Text>
          </>
        )}
        {report.strengthening_suggestions && (
          <>
            <Text style={styles.sectionTitle}>How to Strengthen</Text>
            <Text style={styles.text}>{report.strengthening_suggestions}</Text>
          </>
        )}

        <View style={styles.footer} fixed>
          <Text style={styles.footerText}>Generated by Kill My Idea</Text>
          <Text style={styles.footerText} render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    </Document>
  );
}
